apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app3-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jcrelling/argocd-demo-app3.git
    targetRevision: HEAD
    path: .
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
